import L from 'leaflet';
import * as C from './crypto.mjs';
let api,user,notice,view,vault,key,salt,context,storeKey,chain,timer,map,states=[],markers=[],idleDeadline=0;
const el=id=>document.getElementById(id);
const node=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);return n;};
const field=(id,label,type='text',attrs='')=>`<label for="${id}">${label}</label><input id="${id}" name="${id}" type="${type}" ${attrs}>`;
function run(task){return async event=>{event?.preventDefault();try{notice('');await task(event);}catch(e){notice(e.message);}};}
function bind(id,task){el(id).onsubmit=run(e=>task(Object.fromEntries(new FormData(e.target))));}
function button(id,task){el(id).onclick=run(task);}
const deviceApi=(path,method='GET',body)=>api(path,method,body,{Authorization:`Bearer ${vault.credential}`});
async function save(){localStorage.setItem(storeKey,JSON.stringify(await C.sealVault(vault,key,salt,context)));}
function stop(){clearInterval(timer);if(map){map.remove();map=null;}markers=[];}
function lock(){stop();C.wipe(vault);vault=key=salt=chain=null;}
async function locked(){lock();const saved=localStorage.getItem(storeKey);view.innerHTML=`<section class="card"><h2>${saved?'Unlock this browser.':'Create a browser device.'}</h2><p class="subtle">Private keys stay in a passphrase-protected vault in this browser. Losing it requires new device approval. Only unlock on a browser and server you trust.</p>${!crypto.subtle?'<p>Encryption needs HTTPS (or localhost for testing).</p>':`<form id="vault-form">${saved?'':field('device-name','Browser device name','text','required maxlength="64" value="My browser"')}${field('vault-password','Browser-vault passphrase','password',`required ${saved?'':'minlength="15"'} autocomplete="${saved?'current-password':'new-password'}"`)}<button>${saved?'Unlock map':'Create encrypted device'}</button></form>`}${saved?'<button id="forget-vault" class="danger">Forget this browser device</button>':''}</section>`;if(saved)button('forget-vault',async()=>{if(!confirm('Forget this browser vault? Its keys cannot be recovered. Revoke the old device using another trusted device, then re-enroll this browser.'))return;localStorage.removeItem(storeKey);await locked();});if(!crypto.subtle)return;
 bind('vault-form',async data=>{if(saved){const opened=await C.openVault(JSON.parse(saved),data['vault-password'],context);vault=opened.value;key=opened.key;salt=opened.salt;}else{if(!user.verified)throw new Error('Confirm your account email in Server settings before enrolling a device.');const h=await api('/api/household');vault=C.keys(user.id,h.id,data['device-name']);const registration={domain:'family-stalker.device.v1',household:h.id,...C.identity(vault)};const result=await api('/api/devices/register','POST',{id:vault.id,name:vault.name,signing_key:vault.signing_key,box_key:vault.box_key,signature:C.sign(registration,vault.signing_secret)});vault.credential=result.credential;salt=crypto.getRandomValues(new Uint8Array(16));key=await C.vaultKey(data['vault-password'],salt);await save();}await screen();});}
async function sync(){let after=0,changes=[],r;do{r=await deviceApi(`/api/roster?after=${after}`);changes.push(...r.changes);after=changes.at(-1)?.body.revision||0;if(!r.changes.length&&after<r.revision)throw new Error('Incomplete membership chain.');if(changes.length>10000)throw new Error('Membership exceeds browser limit.');}while(after<r.revision);if(!r.revision)return null;if(!vault.anchor)throw new Error('Verify the owner fingerprint first.');const result=C.verifyChain(changes,vault.household,vault.anchor);if(result.revision<vault.revision||(result.revision===vault.revision&&result.hash!==vault.chain_hash))throw new Error('Membership rollback or fork rejected.');if(!result.current.devices.some(d=>d.id===vault.id))throw new Error('This browser is no longer approved.');vault.revision=result.revision;vault.chain_hash=result.hash;chain=result;await save();return result.current;}
const registration=()=>({domain:'family-stalker.device.v1',household:vault.household,...C.identity(vault)});
async function screen(){stop();idleDeadline=Date.now()+15*60*1000;const d=await deviceApi('/api/device'),h=await api('/api/household');if(!vault.anchor&&h.revision===0&&user.role==='admin'){view.innerHTML=`<section class="card"><h2>Approve your first device.</h2><p>Get the separate local device token through Docker:</p><code>docker compose exec stalker python manage.py device-bootstrap-token</code><form id="bootstrap-device">${field('bootstrap-device-token','Device bootstrap token','password','required autocomplete="off"')}<button>Trust this first device</button></form></section>`;bind('bootstrap-device',async data=>{const body={domain:'family-stalker.roster.v1',household:vault.household,revision:1,previous:'',signer:vault.id,devices:[C.identity(vault)],issued_at:Math.floor(Date.now()/1000)};await deviceApi('/api/roster','POST',{body,signature:C.sign(body,vault.signing_secret),bootstrap_token:data['bootstrap-device-token']});vault.anchor=vault.signing_key;await save();await screen();});return;}
 if(!vault.anchor){view.innerHTML=`<section class="card"><h2>Pair with a trusted device.</h2><p>Compare this device fingerprint on the owner's device before approval:</p><code id="joining-fingerprint"></code><p>Get the household root fingerprint from the owner's trusted device through a separate trusted channel.</p><form id="trust-root">${field('root-fingerprint','Owner household fingerprint','text','required pattern="[a-f0-9]{64}" maxlength="64"')}<button>Verify household</button></form></section>`;el('joining-fingerprint').textContent=C.hash(C.canonical(registration()));bind('trust-root',async data=>{const r=await deviceApi('/api/roster');if(!r.anchor||C.hash(C.unb64(r.anchor))!==data['root-fingerprint'].trim())throw new Error('Household fingerprint does not match.');vault.anchor=r.anchor;await save();await screen();});return;}
 if(d.status!=='approved'){view.innerHTML='<section class="card"><h2>Waiting for trusted approval.</h2><code id="joining-fingerprint"></code><button id="check-approval">Check approval</button></section>';el('joining-fingerprint').textContent=C.hash(C.canonical(registration()));button('check-approval',screen);return;}
 await sync();view.innerHTML=`<section class="card"><h2>Household map</h2><p class="subtle">Locations decrypt here. Fixes older than five minutes are stale.</p><p id="map-status" role="status"></p><div id="household-map" aria-label="Household location map"></div><button id="load-tiles" class="secondary">Load OpenStreetMap tiles</button><p class="subtle">Optional map tiles send the viewed region to OpenStreetMap. No map-provider requests happen until you choose this.</p><div id="location-list"></div><div class="links"><button id="refresh-map">Refresh updates</button><button id="pause-sharing" class="secondary">${d.sharing?'Pause this device':'Resume this device'}</button><button id="browser-gps" class="secondary">Share browser location once</button><button id="delete-history" class="danger">Delete my GPS history</button><button id="lock-map" class="secondary">Lock map</button></div><p class="subtle">Browser GPS requires permission and an active page. Native phone background tracking is separate.</p></section>
 <div class="grid"><section class="card"><h3>Share a location for testing</h3><form id="location-form">${field('location-lat','Latitude','number','required min="-90" max="90" step="any"')}${field('location-lon','Longitude','number','required min="-180" max="180" step="any"')}${field('location-accuracy','Accuracy (metres)','number','required min="0" max="100000" value="10"')}<button>Publish encrypted location</button></form></section><section class="card"><h3>Your map profile</h3><form id="profile-form">${field('profile-name','Display name','text','required maxlength="64"')}${field('profile-photo','Map photo (optional)','file','accept="image/jpeg,image/png,image/webp"')}<button>Save encrypted profile</button></form></section></div>
 <section class="card"><h3>Saved places</h3><form id="place-form">${field('place-name','Place name','text','required maxlength="80"')}${field('place-lat','Place latitude','number','required min="-90" max="90" step="any"')}${field('place-lon','Place longitude','number','required min="-180" max="180" step="any"')}${field('place-radius','Radius (metres)','number','required min="10" max="10000" value="100"')}<button>Save encrypted place</button></form><div id="place-list"></div><button id="reshare-places" class="secondary">Share saved places with newly approved devices</button></section>
 <section class="card"><h3>History and alerts</h3><div class="links"><button id="load-history" class="secondary">Load location history</button><button id="load-events" class="secondary">Load household events</button><button id="more-history" class="secondary" hidden>Load earlier</button></div><div id="history-list"></div></section>
 <section class="card"><h3>Trusted devices</h3><p>Household root fingerprint:</p><code id="root-code"></code><div id="device-list"></div></section>`;
 el('root-code').textContent=C.hash(C.unb64(vault.anchor));el('profile-name').value=user.username;map=L.map('household-map').setView([0,0],2);let tiles=false;button('load-tiles',async()=>{if(!tiles){L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,referrerPolicy:'origin',attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">OpenStreetMap contributors</a>'}).addTo(map);tiles=true;}});
 button('delete-history',async()=>{if(!confirm('Delete your retained GPS locations and events from this server? Previously downloaded copies and backups remain separate.'))return;await deviceApi('/api/records/mine','DELETE',{});await refresh();notice('Your stored location/event history was deleted.');});button('lock-map',locked);button('refresh-map',async()=>{await refresh();await devices();});button('pause-sharing',async()=>{await deviceApi('/api/sharing','PUT',{enabled:!d.sharing});await screen();});button('browser-gps',async()=>{const f=await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:15000,maximumAge:0}));await publish('location',user.id,{lat:f.coords.latitude,lon:f.coords.longitude,accuracy:f.coords.accuracy},'upsert',Math.floor(f.timestamp));await refresh();notice('Encrypted browser location shared.');});
 bind('location-form',async data=>{await publish('location',user.id,point(data['location-lat'],data['location-lon'],data['location-accuracy']));await refresh();notice('Encrypted location published.');});
 bind('profile-form',async data=>{let photo=null,f=el('profile-photo').files[0];if(f){if(f.size>5*1024*1024)throw new Error('Photo must be under 5 MB.');const image=await createImageBitmap(f),canvas=document.createElement('canvas');canvas.width=canvas.height=96;canvas.getContext('2d').drawImage(image,0,0,96,96);image.close();photo=canvas.toDataURL('image/jpeg',0.7);}await publish('profile',user.id,{name:data['profile-name'],photo});await refresh();notice('Encrypted profile saved.');});
 bind('place-form',async data=>{const p=point(data['place-lat'],data['place-lon'],0),radius=Number(data['place-radius']);if(!Number.isFinite(radius)||radius<10||radius>10000)throw new Error('Invalid radius.');await publish('place',C.uuid(),{name:data['place-name'],lat:p.lat,lon:p.lon,radius});await refresh();notice('Encrypted place saved.');});button('reshare-places',async()=>{for(const p of states.filter(p=>p.kind==='place'&&p.operation==='upsert'))await publish('place',p.entity_id,p.data);await refresh();notice('Places encrypted for the current membership.');});
 let cursor=null,kind='location';async function history(nextKind,nextCursor=null){await sync();kind=nextKind;const r=await deviceApi(`/api/records?kind=${kind}&limit=50${nextCursor?`&cursor=${encodeURIComponent(nextCursor)}`:''}`);if(!nextCursor)el('history-list').replaceChildren();for(const record of r.records){const p=C.decryptRecord(record.envelope,vault,chain.rosters);el('history-list').append(node('p',`${new Date(p.captured_at).toLocaleString()} · ${kind==='location'?`${p.data.lat}, ${p.data.lon}`:String(p.data.message||'Household event')}`));}cursor=r.next_cursor;el('more-history').hidden=!cursor;}button('load-history',()=>history('location'));button('load-events',()=>history('event'));button('more-history',()=>history(kind,cursor));await refresh();await devices();timer=setInterval(()=>{if(Date.now()>idleDeadline){locked().catch(e=>notice(e.message));return;}if(document.visibilityState==='visible')refresh().catch(e=>{if(map)markers.forEach(m=>map.removeLayer(m));markers=[];if(el('location-list'))el('location-list').replaceChildren();if(el('map-status'))el('map-status').textContent=`Updates unavailable: ${e.message}`;});},15000);
}
function point(lat,lon,accuracy){const p={lat:Number(lat),lon:Number(lon),accuracy:Number(accuracy)};if(!Number.isFinite(p.lat)||!Number.isFinite(p.lon)||!Number.isFinite(p.accuracy)||Math.abs(p.lat)>90||Math.abs(p.lon)>180||p.accuracy<0||p.accuracy>100000)throw new Error('Invalid location.');return p;}
let pending=Promise.resolve();function publish(kind,entity,data,operation='upsert',capturedAt=Date.now()){const task=async()=>{idleDeadline=Date.now()+15*60*1000;await sync();const d=await deviceApi('/api/device');vault.sequence=Math.max(vault.sequence,d.sequence);const previous=states.find(s=>s.kind===kind&&s.entity_id===entity);const e=C.encryptedRecord(vault,chain.current,kind,entity,data,operation,['place','profile'].includes(kind)?previous?.id||null:null,capturedAt);await deviceApi('/api/records','POST',e);vault.sequence=e.body.sequence;await save();};const next=pending.then(task);pending=next.catch(()=>{});return next;}
async function refresh(){if(!vault)return;await sync();let cursor=null,records=[];do{const r=await deviceApi(`/api/state${cursor?`?cursor=${encodeURIComponent(cursor)}`:''}`);if(r.revision!==chain.revision)throw new Error('Membership changed during refresh.');records.push(...r.records);cursor=r.next_cursor;if(records.length>128)throw new Error('State exceeds browser limit.');}while(cursor);states=records.map(record=>C.decryptRecord(record.envelope,vault,chain.rosters));markers.forEach(marker=>map.removeLayer(marker));markers=[];el('location-list').replaceChildren();el('place-list').replaceChildren();const profiles=new Map(states.filter(p=>p.kind==='profile'&&p.operation==='upsert').map(p=>[p.entity_id,p.data])),points=[];
 for(const p of states.filter(p=>p.kind==='location')){const f=point(p.data.lat,p.data.lon,p.data.accuracy),profile=profiles.get(p.entity_id),name=String(profile?.name||`Member ${p.entity_id.slice(0,8)}`),stale=Date.now()-p.captured_at>300000,icon=node('div');icon.className='map-person';if(profile?.photo&&/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(profile.photo)&&profile.photo.length<30000){const image=node('img');image.src=profile.photo;image.alt='';icon.append(image);}icon.append(node('span',name));const popup=node('div');popup.append(node('strong',name),node('p',`${stale?'Stale':'Recent'} · ${new Date(p.captured_at).toLocaleString()} · ±${f.accuracy} m`));markers.push(L.marker([f.lat,f.lon],{icon:L.divIcon({html:icon,className:stale?'person-marker stale':'person-marker',iconSize:[96,48]})}).addTo(map).bindPopup(popup));points.push([f.lat,f.lon]);el('location-list').append(node('p',`${name}: ${f.lat}, ${f.lon} · ${stale?'stale':'recent'} · ${new Date(p.captured_at).toLocaleString()}`));}
 for(const p of states.filter(p=>p.kind==='place'&&p.operation==='upsert')){const f=point(p.data.lat,p.data.lon,0),radius=Number(p.data.radius);if(!Number.isFinite(radius)||radius<10||radius>10000)throw new Error('Invalid encrypted place.');markers.push(L.circle([f.lat,f.lon],{radius,color:'#a5f0bc'}).addTo(map).bindTooltip(node('span',String(p.data.name))));const row=node('div');row.className='member';row.append(node('span',`${String(p.data.name)} · ${radius} m`));const remove=node('button','Delete');remove.className='danger';remove.onclick=run(async()=>{await publish('place',p.entity_id,{},'delete');await refresh();});const test=node('button','Test arrival');test.className='secondary';test.onclick=run(async()=>{await publish('event',C.uuid(),{type:'arrival',place_id:p.entity_id,message:`Test: arrived at ${String(p.data.name)}`});notice('Encrypted test event published.');});row.append(remove,test);el('place-list').append(row);}
 if(points.length&&!map._stalkerFramed){map.fitBounds(points,{maxZoom:15,padding:[30,30]});map._stalkerFramed=true;}el('map-status').textContent=`${points.length} shared locations · membership revision ${chain.revision} · refreshed ${new Date().toLocaleTimeString()}`;
}
async function roster(devices){await sync();const body={domain:'family-stalker.roster.v1',household:vault.household,revision:chain.revision+1,previous:chain.hash,signer:vault.id,devices:devices.sort((a,b)=>a.id.localeCompare(b.id)),issued_at:Math.floor(Date.now()/1000)};await deviceApi('/api/roster','POST',{body,signature:C.sign(body,vault.signing_secret)});await sync();}
async function devices(){const result=await api('/api/devices');el('device-list').replaceChildren();const removed=new Set(result.devices.filter(d=>d.status==='revoked').map(d=>d.id));if(user.role==='admin'&&chain.current.devices.some(d=>removed.has(d.id))){const reconcile=node('button','Apply account revocations to encryption membership');reconcile.onclick=run(async()=>{await roster(chain.current.devices.filter(d=>!removed.has(d.id)));await devices();notice('Revoked accounts removed from future encryption.');});el('device-list').append(reconcile);}for(const d of result.devices){const row=node('section');row.className='device-row';row.append(node('h4',`${d.name} · ${d.status}`));const fp=C.hash(C.canonical(d.registration));row.append(node('code',fp));if(d.status==='pending'){const label=node('label','Fingerprint shown on the requesting device'),entry=node('input');entry.maxLength=64;label.append(entry);const approve=node('button','Approve trusted device');approve.onclick=run(async()=>{if(entry.value.trim()!==fp)throw new Error('Device fingerprint does not match.');if(!C.verify(d.registration,d.registration_signature,d.signing_key))throw new Error('Device registration rejected.');await roster([...chain.current.devices,{id:d.id,account_id:d.account_id,signing_key:d.signing_key,box_key:d.box_key}]);await devices();notice('Device approved. Reshare places and publish a new location for it.');});row.append(label,approve);}else if(d.status==='approved'&&d.id!==vault.id&&(user.role==='admin'||d.account_id===user.id)){const revoke=node('button','Revoke device');revoke.className='danger';revoke.onclick=run(async()=>{await roster(chain.current.devices.filter(item=>item.id!==d.id));await devices();notice('Device revoked; future encryption uses updated membership.');});row.append(revoke);}el('device-list').append(row);}}
window.FamilyClient={async mount(options){await C.ready;lock();({api,user,notice,view}=options);context=`${location.origin}/${user.id}`;storeKey=`family-stalker.vault.${user.id}`;await locked();},lock(){lock();view=user=null;}};
